### ISSUE TITLE
CODABAR not working

### ISSUE THREAD

**Issue by robertmylne** [picqer/php-barcode-generator#92] opened 2020-01-09 08:49 UTC
When I copy and paste your example:
```
$generator = new Picqer\Barcode\BarcodeGeneratorHTML();
echo $generator->getBarcode('081231723897', $generator::TYPE_CODE_128);
```

Everything works great. But when I change the barcode type to `codabar` it breaks.
```
$generator = new Picqer\Barcode\BarcodeGeneratorHTML();
echo $generator->getBarcode('081231723897', $generator::TYPE_CODABAR);
```

With this error:
```
Line 2038: vendor\picqer\php-barcode-generator\src\BarcodeGenerator.php
ErrorException (E_NOTICE)
Uninitialized string offset: 8
```

I am a bit lost of how to resolve this issue, do you have any ideas? Thank you :)

**Comment by casperbakker** [comment] 2020-01-11 18:54
This works fine here with PHP 7.3. Which PHP version do you use?

It looks like the 2nd char in the code (8) is casted to an integer somewhere, and then it is strictly checked with the possible chars in the array, which only contains the string '8'. But I cannot reproduce this situation.

I added an extra check for this in d96798a2cbf2c8c355130420433fe57ddd76b263, which will be included in the upcoming version. That could fix something like this, but seems illogical to me.

**Closed as completed by casperbakker** 2020-01-11 18:54 UTC

**Comment by robertmylne** [comment] 2020-01-13 01:55
I used a forked package of yours and it worked for me. Thanks anyway.
